### ISSUE TITLE
[todo] 在 PBH 启动之前打开 WebUI 将导致自动刷新失效，并阻止其它页面的后续所有网络请求

### ISSUE THREAD

**Issue by Ghost-chu** [Gaojianli/pbh-fe#113]
![a27b1526de8f23ad623b32662e23e5e2](https://github.com/user-attachments/assets/ea0e2e7c-01f3-4939-a2c5-8288bc25f33d)

以前的版本WebUI打开的时候如果 PBH 没启动，在启动完成后页面可以恢复正常刷新
重构自动刷新之后，如果在加载 manifest 的时候失败了，好像就不会尝试恢复页面了

先打开 WebUI -> 再打开 PBH -> (出现问题) WebUI 停止加载，此时不管再怎么切换，也不会再发起任何新的加载请求。

不知道是不是连接卡住它就不加载其它请求了，还是一个请求失败了就不加载其它请求了。

**Comment by Gaojianli** [comment]
根据设计，启动之前应该打不开webui，你这个场景不存在

**Comment by Ghost-chu** [comment]
> 根据设计，启动之前应该打不开webui，你这个场景不存在

但是首次连接失败的场景是存在的，manifest 不会重试，一次失败就卡住，也没什么提示信息。

**Comment by XiaoXice** [comment]
<img width="381" alt="image" src="https://github.com/user-attachments/assets/75efe16b-d888-4627-9722-a5178b020ed5">

虽然和重构没什么关系，但是还是添加了一个重新连接的功能。 #105
