### ISSUE TITLE
[todo] PBH 许可证状态未被记录在 LocalStroage 中

### ISSUE THREAD

**Issue by Ghost-chu** [Gaojianli/pbh-fe#117]
当刷新页面时，会提示 此图表需要订阅 PeerbanHelper+ 才能查看 提示信息，需要等待数秒 WebUI 确认许可证状态后才会显示图表。
但问题在于，每次刷新都会弹出这个提示，体验太差了。Debug 的时候等的非常难过 :(

**Comment by Gaojianli** [comment]
> 当刷新页面时，会提示 此图表需要订阅 PeerbanHelper+ 才能查看 提示信息，需要等待数秒 WebUI 确认许可证状态后才会显示图表。 但问题在于，每次刷新都会弹出这个提示，体验太差了。Debug 的时候等的非常难过 :(

这东西不能缓存，我可以调整时间

**Comment by Ghost-chu** [comment]
> > 当刷新页面时，会提示 此图表需要订阅 PeerbanHelper+ 才能查看 提示信息，需要等待数秒 WebUI 确认许可证状态后才会显示图表。 但问题在于，每次刷新都会弹出这个提示，体验太差了。Debug 的时候等的非常难过 :(
> 
> 这东西不能缓存，我可以调整时间

缓存之后全局监听 402 再刷新是不是也行

**Comment by Ghost-chu** [comment]
乐观缓存+后台刷新我觉得也可以的
