### ISSUE TITLE
pbh的内置webui

### ISSUE THREAD

**Issue by dead-circuit** [Gaojianli/pbh-fe#119]

**Comment by Gaojianli** [comment]
？

**Comment by Gaojianli** [comment]
你没有浏览器吗？

**Comment by dead-circuit** [comment]
![屏幕截图 2024-08-16 150540](https://github.com/user-attachments/assets/fa1c55f2-7b91-4dc2-bedb-d6affb06b3ca)
![屏幕截图 2024-08-16 150333](https://github.com/user-attachments/assets/b59fba7f-a86d-4fd1-90de-558f8d160823)

**Comment by dead-circuit** [comment]
我已经再config.yaml里面将IP设置与qbee的ip对应了

**Comment by Ghost-chu** [comment]
> 我已经再config.yaml里面将IP设置与qbee的ip对应了

版本升级后打开可能会白屏，是目前正式版已知问题，请清除浏览器缓存后再试。

**Comment by dead-circuit** [comment]
可以了 感谢解答
