### ISSUE TITLE
[Bug] popup-max-height=false 不生效

### ISSUE THREAD

**Issue by Gaojianli** [Gaojianli/pbh-fe#125]
![image](https://github.com/user-attachments/assets/87775930-9487-4ccb-a0c1-64fa242765f6)
如图所示，这里不应该出现滚动条

**Comment by XiaoXice** [comment]
鉴定为：
人有和羹者，以杓尝之，少盐，便益之。后复尝之向杓中者，故云：“盐不足。”如此数，益升许盐，故不咸，因此为怪。
