### ISSUE TITLE
封禁名单（banlist)页面feed流存在问题

### ISSUE THREAD

**Issue by Gaojianli** [Gaojianli/pbh-fe#34]
1. 在关闭自动刷新的情况下，每次滚动发送了2次请求：
![telegram-cloud-photo-size-5-6327602440924413449-y](https://github.com/PBH-BTN/pbh-fe/assets/19235246/59bc3832-64a0-4cc7-97d8-f8313664c50f)
2. 在列表只有一项的时候，会无限触发获取新的数据，造成资源消耗
![telegram-cloud-photo-size-5-6327602440924413494-y](https://github.com/PBH-BTN/pbh-fe/assets/19235246/296516c7-3562-4d52-8299-6f7c58f006d9)

**Comment by XiaoXice** [comment]
![image](https://github.com/user-attachments/assets/ff0b2b79-3044-4c0d-a406-079fd17e2833)
使用Charles模拟没有发现问题2，需要更多信息。
