### ISSUE TITLE
随便糊了个logo草图

### ISSUE THREAD

**Issue by Kaffu-Chino** [Gaojianli/pbh-fe#35]
RT，颜色参考的qb的logo，可以的话我就画一下矢量图
![image](https://github.com/PBH-BTN/pbh-fe/assets/65818132/6e5e9747-a5d4-4414-85b9-1ed13fce990d)

**Comment by Gaojianli** [comment]
不要色吧，带颜色的对深色模式浅色模式不友好

**Comment by Kaffu-Chino** [comment]
> 不要色吧，带颜色的对深色模式浅色模式不友好

做ico问题不大吧
