### ISSUE TITLE
高分辨率屏下图表显示溢出

### ISSUE THREAD

**Issue by Kaffu-Chino** [Gaojianli/pbh-fe#40]
RT
![image](https://github.com/PBH-BTN/pbh-fe/assets/65818132/0c487211-0556-4c82-bfcd-d0a3507d404e)

**Comment by Gaojianli** [comment]
你能修一下吗

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："Kaffu&nbsp;Chino ***@***.***&gt;;
发送时间：2024年7月3日(星期三) 晚上10:52
收件人："PBH-BTN/pbh-fe" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[PBH-BTN/pbh-fe] 高分辨率屏下图表显示溢出 (Issue #40)
-----------------------------------

 

 
RT
 image.png (view on web)
