### ISSUE TITLE
OOBE 页面端点需要统一

### ISSUE THREAD

**Issue by Ghost-chu** [Gaojianli/pbh-fe#69]
## 问题1

现在 OOBE 过程使用 DownloaderController 的接口测试下载器，但又使用 OOBE Init 的接口创建下载器，这太奇怪了！  
在 OOBE 阶段，PBH 应该拒绝任何 OOBE 接口以外的接口访问（因为此时没有鉴权保护）。

* 方案1：克隆一份相同接口到 OOBE 里用于测试下载器
* 方案2：创建下载器不使用 OOBE 接口，而是直接用 DownloaderController 的接口，然后 OOBE 阶段关闭鉴权
* 方案3：不在 OOBE 里处理下载器

## 问题2

目前展示 OOBE 页面的方式也很 hack，而且用户一旦访问过正式仪表盘，随后重置配置文件，后端再 redirect 到 /init 根本不起任何效果…… 必须清除缓存再试才行。前端能否像检查登录是否已登录一样，额外监听一个状态码？

```
HTTP/1.1 GET /path/to/api

303 See Other
Location: /init

{"message": "PeerBanHelper 需要 OOBE 向导初始化", "location": "/init"}
```

**Comment by Gaojianli** [comment]
那就用方案1
