### ISSUE TITLE
默认启用下载器增量封禁开关

### ISSUE THREAD

**Issue by Ghost-chu** [Gaojianli/pbh-fe#71]
自 v6 开始，qBittorrent 的增量封禁随机性封不掉 Peer 的问题得到了修复。现在完全可以推荐开启增量封禁选项。性能更好，并且不会给 qBittorrent 上压力。

**Comment by Gaojianli** [comment]
修复的原因是？之前不是因为qbt bug吗

**Comment by Ghost-chu** [comment]
> 修复的原因是？之前不是因为qbt bug吗

是 PBH 的 BUG，IP 地址串被转换了一次 QB 不认了。~~虽然现在还有偶发封不掉的情况~~这个偶发是 QB 自己的问题，但我 workaround 了下：https://github.com/PBH-BTN/PeerBanHelper/commit/0bd7a8ec7dd207e17e28d7dc136a959cfebe39e6
