### ISSUE TITLE
鼠标气泡悬停时，气泡不应该自行消失

### ISSUE THREAD

**Issue by Ghost-chu** [Gaojianli/pbh-fe#89]
如图所示的气泡有时会用来显示返回的错误信息，但显示时间太短，经常来不及选中复制内容。如果鼠标悬停在上面进行操作时不会自动消失，对于复制错误信息和截图都会有很大帮助。

![image](https://github.com/user-attachments/assets/77a64853-1f4e-4ed4-9abc-adb060f399c9)

**Comment by Gaojianli** [comment]
实现有难度，官方不太支持

**Comment by Ghost-chu** [comment]
> 实现有难度，官方不太支持

![image](https://github.com/user-attachments/assets/9285384f-431e-4fba-b60a-f3a0058d39c4)

2.39.0 好像支持了
