### ISSUE TITLE
[开发快照] [BUG] 规则订阅页面关闭特定规则后，规则数量显示为 NaN

### ISSUE THREAD

**Issue by Ghost-chu** [Gaojianli/pbh-fe#96]
![4d48fac1-5e6d-48ef-942f-bf5aa6379761](https://github.com/user-attachments/assets/f95f4085-a450-4254-bbee-987db7c0c9dd)

**Comment by Ghost-chu** [comment]
问题仍然存在
![56a974f6e7b6abc903d8d340857656da](https://github.com/user-attachments/assets/6dc0501e-998b-4bc7-b6f4-fc2208b6d205)

**Comment by Gaojianli** [comment]
这个是故意的吧，因为如果不启用这个有可能是0，所以是无效的，这里的问题是我写错了，应该是N/A
